language: c

compiler:
  - gcc
  - clang

os:
  - linux

env:
  - ARCH=x86_64
  - ARCH=i386

before_install:
  - gpg --recv-keys 3CEA9B8868BC3852618EB5B4707F91A424F006F5
  - wget http://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.2.tar.bz2
  - wget http://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.2.tar.bz2.sig
  - gpg --trust-model always --verify libftdi1-1.2.tar.bz2.sig
  - tar -xjf libftdi1-1.2.tar.bz2

install:
  - cd libftdi1-1.2
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo apt-get update -qq;
      if [ "$ARCH" = "x86_64" ];
      then
        sudo apt-get install -qq libusb-1.0-0-dev;
      elif [ "$ARCH" = "i386" ];
      then
        sudo apt-get install -qq gcc-multilib libusb-1.0-0-dev:i386 pkg-config:i386;
        export CFLAGS="-m32";
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      brew update;
      brew install libusb;
    fi
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - cd ../../

script:
  - make

