language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i386

before_install:
  - wget https://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.4.tar.bz2
  - tar -xjf libftdi1-1.4.tar.bz2

install:
  - cd libftdi1-1.4
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo apt-get update -qq;
      if [ "$ARCH" = "x86_64" ];
      then
        sudo apt-get install -qq libusb-1.0-0-dev;
      elif [ "$ARCH" = "i386" ];
      then
        sudo apt-get install -qq gcc-multilib libusb-1.0-0-dev:i386 pkg-config:i386;
        export CFLAGS="-m32";
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      brew update;
      brew install libusb;
    fi
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - cd ../../

script:
  - mkdir build
  - cd build
  - cmake ../
  - make 
  - sudo make install/strip
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$ARCH" = "x86_64" ] ;
    then
	cd ..; 
	mkdir mingw32;
	cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../cmake/Toolchain-cross-mingw32.cmake ..;
	make;
    fi
  - /usr/local/bin/fujprog -h
